routes/web.php
        return view('test.vnpay-response');
    })->name('vnpay-response');
    Route::get('/host', function () {
        return view('welcome');
    });
});

Route::get('sign-in', 'UserInBOController@loginUser');
Route::post('sign-in', 'UserInBOController@loginUser');
Route::get('sign-out', 'UserInBOController@logoutUser');
Route::post('sign-out', 'UserInBOController@logoutUser');
Route::get('ajax', 'AjaxController@SetProcess');
Route::post('ajax', 'AjaxController@SetProcess');

Route::get('customer/confirm', 'CustomerInBoController@Confirm');

Route::group(['middleware' => 'guest'], function () {
    Route::group(['prefix' => 'my-report'], function () {
        Route::get('/bill', 'ReportController@getBillReport')->name('report-bill');
        Route::post('/bill', 'ReportController@submitBillReport');
        Route::get('/bill-template', 'ReportController@downloadBillTemplate')->name('bill-report-template');
        Route::post('/bill-import', 'ReportController@importBillReport')->name('import-bill-report');
        Route::get('/compose/{from}/{to}', 'ReportController@composeReportPost')->name('compose-report');
    });


    Route::get('report/{type}/{action}', 'ReportController@index');
    Route::get('customer', 'CustomerInBoController@getAllCustomer');
    Route::get('customer/addedit', 'CustomerInBoController@addEditCustomer');
    Route::post('customer/addedit', 'CustomerInBoController@addEditCustomer');
    Route::get('customer/import', 'ImportExcelController@ImportCustomer');
    Route::post('customer/import', 'ImportExcelController@ImportCustomer');
    Route::get('customer/tranfer-customer', 'CustomerInBoController@tranferCustomerRecent');
    Route::post('customer/tranfer-customer', 'CustomerInBoController@tranferCustomerRecent');
    Route::get('offical_customer', 'CustomerInBoController@getAllOfficalCustomer');
    Route::get('offical_customer/edit', 'CustomerInBoController@EditOfficalCustomer');
    Route::post('offical_customer/edit', 'CustomerInBoController@EditOfficalCustomer');
    Route::get('customer/file_management', 'CustomerInBoController@listFileManagement');
    Route::post('customer/file_management', 'CustomerInBoController@listFileManagement');

    //bank
    Route::get('bank', 'BankInfoController@getAllBankInfo');
    Route::get('bank/addedit', 'BankInfoController@addEditBankInfo');
    Route::post('bank/addedit', 'BankInfoController@addEditBankInfo');

    //paymentMethod
    Route::get('payment_medthod', 'PaymentMethodController@getAllPayMentMethod');
    Route::get('payment_medthod/addedit', 'PaymentMethodController@addEditPayMentMethod');
    Route::post('payment_medthod/addedit', 'PaymentMethodController@addEditPayMentMethod');
    Route::get('payment/print', 'PaymentController@print');

    //role group
    Route::get('role_groups', 'RoleGroupController@getAllRoleGroup');
    Route::get('role_group/addedit', 'RoleGroupController@addEditRoleGroup');
    Route::post('role_group/addedit', 'RoleGroupController@addEditRoleGroup');

    Route::group(['prefix' => 'roles'], function () {
        Route::get('/', 'RoleController@index')->name('role-list');
        Route::get('/form', 'RoleController@addEditRole')->name('role-form');
        Route::post('/form', 'RoleController@addEditRole');

        Route::get('config-app-menu', 'RoleController@ConfigRoleMenu')->name('app-menu-config');
        Route::post('config-app-menu', 'RoleController@ConfigRoleMenu');
        Route::get('app-menu', 'RoleController@getAllRoleMenu')->name('app-menu');
        Route::post('app-menu', 'RoleController@getAllRoleMenu');

        Route::get('web-menu', 'RoleController@getAllRoleMenuWeb')->name('web-menu');
        Route::get('config-web-menu', 'RoleController@editRoleMenuWeb')->name('web-menu-config');
        Route::post('config-web-menu', 'RoleController@editRoleMenuWeb');
    });
    Route::get('getRolebyUserId', 'RoleController@getRoleMenuByUserId');

    Route::get('payment/addnew', 'PaymentController@addNewPayment');
    Route::post('payment/addnew', 'PaymentController@addNewPayment');

    /** Payment Group */
    Route::group(['prefix' => 'payment'], function () {
        Route::get('/', 'PaymentController@index')->name('list-payment');
        Route::get('/form/{id}', 'PaymentController@showForm')->name('show-payment')->where('id', '[0-9]+');
        Route::post('/form/{id}', 'PaymentController@submitForm')->name('submit-payment')->where('id', '[0-9]+');
    });
    /** End Payment Group */

    // UserInBO
    Route::get('userBO', 'UserInBOController@getAllUserInBO');
    Route::get('userBO/addedit', 'UserInBOController@addEditUserInBO')->name('user-form');
    Route::post('userBO/addedit', 'UserInBOController@addEditUserInBO');

    //import UserInBo

    Route::get('importUser', 'UserInBOController@ImportUser');
    Route::post('importUser', 'UserInBOController@ImportUser');

    //import UserInBo
    Route::get('importUserChild', 'UserInBOController@ImportUserChild');
    Route::post('importUserChild', 'UserInBOController@ImportUserChild');

    Route::get('importGroups', 'UserInBOController@ImportUserGroups');
    Route::post('importGroups', 'UserInBOController@ImportUserGroups');

    Route::get('importProject', 'ImportExcelController@ImportProject');
    Route::post('importProject', 'ImportExcelController@ImportProject');
    Route::get('importBuilding', 'ImportExcelController@ImportBuilding');
    Route::post('importBuilding', 'ImportExcelController@ImportBuilding');
    Route::get('importProduct', 'ImportExcelController@ImportProduct');
    Route::post('importProduct', 'ImportExcelController@ImportProduct');

    ///Bảng hàng///
    Route::get('apartment', 'ProductController@getAllApartment');
    Route::get('apartment/import', 'ProductController@importApartment');
    Route::post('apartment/import', 'ProductController@importApartment');
    Route::get('apartment/export', 'ProductController@exportApartment');

    ///Book online///
    Route::get('transaction', 'TransactionController@getAllTransaction')->name('list-transaction');
    Route::get('transaction/confirm', 'TransactionController@confirm');
    Route::get('transaction/changeStatus', 'TransactionController@changeStatus');

    Route::group(['prefix' => 'bill'], function () {
        Route::get('/', 'BillController@getAllBill')->name('list-bill');
        Route::get('/confirm', 'BillController@confirm');
        Route::get('/changeStatus', 'BillController@changeStatus');
    });

    Route::get('template_email', 'TemplateEmailController@index');
    Route::get('template_email/addedit', 'TemplateEmailController@addedit');
    Route::post('template_email/addedit', 'TemplateEmailController@addedit');

    Route::get('pdf/index', 'PdfController@index');

//        Route::get('chat/index', 'ChatController@index');

    //customer notice
    Route::get('customer_notice/list', 'CustomerNoticeController@getAllCustomerNotice');
    Route::get('customer_notice/addedit', 'CustomerNoticeController@addEditCustomerNotice');
    Route::post('customer_notice/addedit', 'CustomerNoticeController@addEditCustomerNotice');

    // POLL
    Route::get('poll/add', 'PollController@addEditPoll');
    Route::post('poll/add', 'PollController@addEditPoll');

    ///Category//
    Route::get('category', 'CategoryController@index');
    Route::get('category/addedit', 'CategoryController@addEdit');
    Route::post('category/addedit', 'CategoryController@addEdit');

    ///Investor//
    Route::get('investor', 'InvestorController@index');
    Route::get('investor/addedit', 'InvestorController@addEdit');
    Route::post('investor/addedit', 'InvestorController@addEdit');

    // sync All Project
    Route::get('syncProduct', 'ProductController@syncAllProduct');
    Route::post('syncProduct', 'ProductController@syncAllProduct');

    // sync Price List
    Route::get('syncPriceList', 'ProductController@syncPriceList');
    Route::get('udpateCategory', 'ProductController@updatecategoryId');

    // Craw price form TVC to BO
    Route::get('crawPrice', 'ProductController@crawPrice');
    Route::post('crawPrice', 'ProductController@crawPrice');
    Route::get('crawProduct', 'ProductController@crawProductFromTvcToBO');
    Route::post('crawProduct', 'ProductController@crawProductFromTvcToBO');
    Route::get('processcrawProduct', 'ProductController@ProcessCrawProduct');

    // Post
    Route::group(['prefix' => 'post'], function () {
        Route::get('/', 'PostController@index')->name('post-list');
        Route::get('/form/{id?}', 'PostController@postForm')->name('post-form');
        Route::post('/form/{id?}', 'PostController@submitForm');
        Route::post('/{id}/delete', 'PostController@delete')->name('post-delete');
        Route::get('/{id}/feedbacks', 'PostController@getFeedbacks')->name('post-feedbacks')->where(['id' => '[0-9]+']);
    });
});

Route::group(['prefix' => 'noi-bo'], function () {
    Route::get('trang-chu', 'Frontend\HomeController@index');
});

Route::get('renewSession', 'API\APIController@__TVC_RENEW_SESSION');
// SYNC DATA TVC
Route::get('syncProjectTVC', 'CategoryController@syncAPIProjectTVC');
Route::post('syncProjectTVC', 'CategoryController@syncAPIProjectTVC');
Route::get('syncBuildingTVC', 'CategoryController@syncAPIBuildingTVC');
Route::post('syncBuildingTVC', 'CategoryController@syncAPIBuildingTVC');
Route::get('syncProductTVC', 'ProductController@syncAPIProductTVC');
Route::post('syncProductTVC', 'ProductController@syncAPIProductTVC');

//Sync bank
Route::get('syncBankTVC', 'BankInfoController@syncAPIBankTVC');
Route::post('syncBankTVC', 'BankInfoController@syncAPIBankTVC');

//Route::get('abcd', 'RoleController@getRoleMenuByUserId');

Route::get('/home', 'HomeController@index')->name('home');
// get image

Route::get('get_singnature', 'UserInBOController@getSignature');

Route::get('admin', function () {
    return redirect('/sign-in');
});
Route::get('/{path?}', function () {
    return view('APP.index');

app/ForumPost.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class ForumPost extends Model
{
    public function getImagesAttribute($value) {
        if ($value) {
            $value = json_decode($value)->value;
            foreach ($value as &$item) {
                $item = asset($item);
            }
        }
        return $value;
    }
    public function getLikesAttribute($value) {
        return $value? json_decode($value)->value : null;
    }
    public function getDislikesAttribute($value) {
        return $value? json_decode($value)->value : null;
    }
    public function getTagsAttribute($value) {
        return $value? json_decode($value)->value : null;
    }
    public function getCreatedAtAttribute($value) {
        return $value? Util::timeAgo($value) : $value;
    }
    public function getCreatedByAttribute($value) {
        return $this->is_anonymous? null : $value;
    }

    /**
     * @param $key
     * @param $value
     */
    public function setAttribute($key, $value) {
        switch ($key) {
            case 'images':
            case 'likes':
            case 'dislikes':
            case 'tags':
                $this->attributes[$key] = $value? json_encode(['value' => array_values($value)]) : null;
                break;
            default:
                $this->attributes[$key] = $value;
        }
    }

    public function author() {
        return $this->belongsTo(BOUser::class, 'created_by', BOUser::ID_KEY);
    }

    public function feedbacks() {
        return $this->hasMany(ForumFeedback::class, 'forum_post_id');
    }
}

app/Http/Controllers/InvestorController.php
<?php
namespace App\Http\Controllers;
use App\BOBill;
use App\BOInvestor;
use Illuminate\Http\Request;
class InvestorController extends Controller
{
    public function index() {

        /** @var $query */
//        $query = BOBill::where([BOBill::ID_KEY => '1544608997'])
//            ->with([
//                'staff' => function($staff) {
//                    $staff->select([
//                        'ub_id',
//                        'ub_title AS name',
//                        'ub_account_name AS account',
//                        'ub_email AS email',
//                        'ub_avatar AS avatar',
//                        'signature',
//                        'ub_tvc_code',
//                        "group_ids",
//                        'ub_account_tvc'
//                    ])
//                        ->with(["group" => function($group) {
//                            return $group->select(["gb_title"]);
//                        }]);
//                },
//                'transaction' => function($transaction) {
//                    $transaction->select([
//                        'trans_id', 'trans_deposit AS deposit_amount', 'staff_code'
//                    ]);
//                },
//                'product' => function($apartment) {
//                    return $apartment->select([
//                        "pb_id",
//                        "pb_title AS apartment", "pb_code AS code",
//                        "category_id", "pb_required_money",
//                        "pb_required_money AS required_money",
//                        "pb_used_s", "pb_built_up_s", "pb_code_real", "pb_price_total",
//                        "price_used_s","pb_price_per_s",
//                        "stage", "book_type"
//                    ]);
//                },
//            ])->first();
//        MailController::customerContract($query, BOBill::STATUSES['STATUS_APPROVED_BY_MANAGER']);
//die('dang gui mail day');
        $investors = BOInvestor::paginate(30);
        $a_DataView['investors'] = $investors;
        return view('investor.index',$a_DataView);
    }

    public function addEdit(Request $request) {
        $investorId = $request->input('id', 0);
        $submit = $request->input('submit');
        $a_DataView['investorId'] = $investorId;
        if($investorId != 0){
            $investor = BOInvestor::find($investorId);
            if($investor) $a_DataView['investor'] = $investor;
        }else{
            $investor = new BOInvestor();
        }
        if (isset($submit) && $submit != "") {
            $investor->code = $request->input('code');
            $investor->name = $request->input('name');
            if($investor->save()){
                return redirect('investor')->with('status', 'Cập nhật thành công!');
            }
        }
        return view('investor.addedit',$a_DataView);
    }
}

resources/views/investor/addedit.blade.php
@extends('layouts.admin.layoutAdmin')
@section('content')

    <h3 class="col-xs-12 no-padding text-uppercase"><?php echo $investorId == 0 ? 'Thêm Chủ đầu tư' : 'Sửa chủ đầu tư' ?></h3>
    <div class="alert alert-danger hide backend"></div>
    <form id="fileupload" class="form-horizontal" method="post" action="">
        <input type="hidden" name="_token" value="{!! csrf_token() !!}">
        <div class="form-group">
            <div class="col-xs-12 col-sm-6 no-padding">
                <label for="code" class="col-xs-12 col-sm-3 control-label text-left">Mã chủ đầu tư</label>
                <div class="col-xs-12 col-sm-9 no-padding">
                    <input id="code" name="code" type="text" value="<?php echo isset($investor) ? $investor->code : "" ?>" class="form-control check-duplicate" required/>
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-12 col-sm-6 no-padding">
                <label for="name" class="col-xs-12 col-sm-3 control-label text-left">Tên chủ đầu tư</label>
                <div class="col-xs-12 col-sm-9 no-padding">
                    <input id="name" name="name" field-name="Tên" type="text" value="<?php echo isset($investor) ? $investor->name : "" ?>" class="form-control" required />
                </div>
            </div>
        </div>
        <div class="form-group">
            <div class="col-xs-6 col-sm-3 no-padding text-right">
                <input type="submit" name="submit" class="btn btn-primary" value="Cập nhật">
            </div>
        </div>
    </form>
@endsection

resources/views/investor/index.blade.php
@extends('layouts.admin.layoutAdmin')
@section('content')
    <h3 class="col-xs-12 no-padding text-uppercase">Danh sách Chủ đầu tư</h3>
    <br>
    <div>
        <a class="btn btn-primary" href="/investor/addedit">Thêm chủ đầu tư mới</a>
    </div>
    <div class="">
        <table class="table table-responsive table-hover table-bordered">
            <tr class="header-tr">
                <td class="bg-success"><strong>STT</strong></td>
                <td class="bg-success"><strong>Mã</strong></td>
                <td class="bg-success"><strong>Tên chủ đầu tư</strong></td>
                <td class="bg-success"><strong>Ngày tạo</strong></td>
                <td class="bg-success"><strong>Ngày sửa</strong></td>
                <td class="bg-success"><strong>Action</strong></td>
            </tr>
            @foreach ($investors as $index => $investor)
                <tr>
                    <td>    {{ $index + 1 }}</td>
                    <td>    {{ $investor->code }}</td>
                    <td>    {{ $investor->name }}</td>
                    <td>    {{ $investor->created_at }}</td>
                    <td>    {{ $investor->updated_at }}</td>
                    <td>
                        <a title="Edit" href="<?php echo Request::root().'/investor/addedit?id='.$investor->id;?>" title="Edit" class="not-underline">
                            <i class="fa fa-edit fw"></i>
                        </a>
                        <a id="trash_switch_" href="javascript:GLOBAL_JS.v_fDelRow({{ $investor->id }},1,'cb_status')" title="Cho vào thùng rác" class="not-underline">
                            <i class="fa fa-trash fa-fw text-danger"></i>
                        </a>&nbsp;
                    </td>
                </tr>
            @endforeach
        </table>
    </div>

    <!--Hidden input-->
    <input type="hidden" name="tbl" id="tbl" value="b_o_categories">
    <?php echo $investors->render()?>
@endsection